import { AiSurface, Banner, Layer, closeLayers, openLayer, setParams, useDemoState, useLocation } from '@portfolio/remote-runtime';
import { compatible, diff, type Change, type JsonSchema, type TopicReport } from '@portfolio/events/compat';
import generated from '@portfolio/events/contracts-report.json';
import v2 from '@portfolio/events/schemas/delivery.updated/v2.json';

/** Generated by the CI checker (packages/events/src/compat.test.ts); never edited by hand. */
const report = generated as unknown as { topics: TopicReport[] };

const kindLabel: Record<string, string> = { removed: 'removed', added: 'added', 'type-changed': 'type changed', 'now-required': 'now required', 'now-optional': 'now optional', 'enum-narrowed': 'enum narrowed', 'enum-widened': 'enum widened' };

/** The expand step of expand → migrate → contract: v3 keeps etaMinutes and carrier, adds the new fields as optional. */
function expandSchema(): JsonSchema {
  const schema = structuredClone(v2) as unknown as JsonSchema;
  const payload = schema.properties!.payload!;
  payload.properties = { ...payload.properties, carrierId: { type: 'string' }, eta: { type: 'object', required: ['earliest', 'latest'], properties: { earliest: { type: 'string' }, latest: { type: 'string' } } } };
  return schema;
}

export function Contracts() {
  const state = useDemoState();
  const { params } = useLocation();
  const selectedTopic = report.topics.find((topic) => topic.topic === (params.get('topic') ?? 'delivery.updated')) ?? report.topics[0]!;
  const transition = selectedTopic.transitions.at(-1);
  const breaking = transition?.changes.filter((change) => change.breaks.length) ?? [];
  const broken = selectedTopic.consumers.filter((consumer) => consumer.breaks.length);
  const safe = selectedTopic.consumers.filter((consumer) => !consumer.breaks.length);
  const isProposal = Boolean(selectedTopic.proposed);

  return (
    <main class="ms-main" id="mesh-contracts">
      <section class="ms-page-head" data-anchor="ms-contracts-head">
        <div>
          <h1>contracts</h1>
          <p class="ms-muted">schema registry · {report.topics.length} topics · consumer-driven contracts from {new Set(report.topics.flatMap((topic) => topic.consumers.map((consumer) => consumer.consumer))).size} readers · checked in ci on every pr</p>
        </div>
      </section>
      {state === 'error' && <Banner tone="risk" icon="!" title="registry unreachable · showing the report from the last ci run" anchor="ms-contracts-error">producers keep publishing with cached schemas; new versions cannot be registered until it returns.</Banner>}

      <div class="ms-contracts">
        <section class="ms-panel" aria-labelledby="registry-title" data-anchor="ms-registry">
          <header><h2 id="registry-title">registry</h2><span class="ms-muted">json schema · tolerant readers</span></header>
          <table class="ms-table">
            <thead><tr><th>topic</th><th>version</th><th>format</th><th>consumers</th><th>compatibility</th><th>status</th></tr></thead>
            <tbody>
              {report.topics.map((topic) => (
                <tr key={topic.topic} class={`${topic.topic === selectedTopic.topic ? 'selected' : ''} ${topic.status === 'blocked' ? 'fail' : ''}`}>
                  <td><button type="button" class="ms-link" aria-pressed={topic.topic === selectedTopic.topic} onClick={() => setParams({ topic: topic.topic })}>{topic.topic}</button></td>
                  <td>{topic.current}{topic.proposed && <span class="ms-proposed"> → {topic.proposed.replace('.proposed', '')} pr</span>}</td>
                  <td class="muted">{topic.format}</td>
                  <td>{topic.consumers.length}</td>
                  <td class="muted">{topic.mode.toLowerCase()}</td>
                  <td><span class={`ms-circuit ${topic.status === 'blocked' ? 'open' : 'closed'}`}>{topic.status}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        <section class="ms-panel ms-pr" aria-labelledby="pr-title" data-anchor="ms-contract-diff">
          <header>
            <h2 id="pr-title">{isProposal ? `pr #212 · ${selectedTopic.topic} ${selectedTopic.proposed?.replace('.proposed', '')}` : `${selectedTopic.topic} · ${transition ? `${transition.from} → ${transition.to}` : selectedTopic.current}`}</h2>
            <span class={`ms-check ${selectedTopic.status === 'blocked' ? 'fail' : 'pass'}`}>{selectedTopic.status === 'blocked' ? '✕ contracts / compatibility' : '✓ contracts / compatibility'}</span>
          </header>
          <p class="ms-muted">{selectedTopic.proposedDescription ?? selectedTopic.description}</p>
          {transition ? (
            <ul class="ms-diff" aria-label="field changes">
              {transition.changes.map((change: Change) => (
                <li key={change.path + change.kind} class={`${change.kind} ${change.breaks.length ? 'breaking' : ''}`}>
                  <span class="ms-diff-sign" aria-hidden="true">{change.kind === 'removed' ? '−' : change.kind === 'added' ? '+' : '~'}</span>
                  <code>payload.{change.path}</code>
                  <span class="ms-diff-kind">{kindLabel[change.kind]}{change.before ? ` · ${change.before}` : ''}{change.after ? ` → ${change.after}` : ''}</span>
                  {change.breaks.length > 0 && <b class="ms-breaks">breaks {change.breaks.join(' + ')}</b>}
                </li>
              ))}
            </ul>
          ) : <p class="ms-muted">single version · nothing to compare</p>}
          <p class={`ms-verdict ${selectedTopic.status === 'blocked' ? 'bad' : 'ok'}`} data-anchor="ms-ci-verdict">
            {selectedTopic.status === 'blocked'
              ? `blocked by ci: ${breaking.length} breaking change${breaking.length === 1 ? '' : 's'} under ${selectedTopic.mode.toLowerCase()} and ${broken.length} consumer${broken.length === 1 ? '' : 's'} still read removed fields`
              : `compatible under ${selectedTopic.mode.toLowerCase()} · no consumer reads a removed field`}
          </p>
        </section>
      </div>

      <div class="ms-contracts">
        <section class="ms-panel" aria-labelledby="consumers-title" data-anchor="ms-consumers">
          <header><h2 id="consumers-title">consumers of {selectedTopic.topic}</h2><span class="ms-muted">declared in each package's contracts.json</span></header>
          <ul class="ms-consumers">
            {[...broken, ...safe].map((consumer) => (
              <li key={consumer.consumer} class={consumer.breaks.length ? 'breaks' : 'safe'}>
                <span class={consumer.breaks.length ? 'bad' : 'ok'} aria-hidden="true">{consumer.breaks.length ? '✕' : '✓'}</span>
                <div>
                  <b>{consumer.consumer}</b> <small class="ms-muted">{consumer.owner}</small>
                  <p>{consumer.breaks.length ? <>reads <code>{consumer.breaks.join(', ')}</code> · breaks</> : <>reads {consumer.reads.join(', ')} · safe</>}</p>
                </div>
              </li>
            ))}
          </ul>
        </section>

        {isProposal ? (
          <AiSurface title="safer rollout · expand, migrate, contract" meta="migration planner · 0.9" anchor="ms-rollout" className="ms-ai"
            sources={[{ label: 'contracts report · this pr', score: 0.98 }, { label: 'consumer read logs · 14 d', score: 0.9 }, { label: 'v1 → v2 rollout', score: 0.84 }]}
            actions={<button type="button" class="ai-approve" onClick={() => openLayer({ modal: 'rollout' })}>draft the three prs</button>}>
            <ol class="ms-plan">
              <li><b>expand</b> · ship v3 with <code>eta</code> and <code>carrierId</code> as optional fields next to <code>etaMinutes</code> and <code>carrier</code> (deprecated)</li>
              <li><b>migrate</b> · move {broken.map((consumer) => consumer.consumer).join(', ')} to the new fields; watch read logs</li>
              <li><b>contract</b> · v4 removes the deprecated fields after 14 days with zero reads</li>
            </ol>
          </AiSurface>
        ) : (
          <AiSurface title="nothing to plan" meta="migration planner" anchor="ms-rollout" className="ms-ai">
            this topic's latest change is compatible and every consumer is safe.
          </AiSurface>
        )}
      </div>

      {params.get('modal') === 'rollout' && <Rollout />}
    </main>
  );
}

function Rollout() {
  const expand = expandSchema();
  const changes = diff(v2 as unknown as JsonSchema, expand);
  const backward = compatible(changes, 'BACKWARD');
  const full = compatible(changes, 'FULL');
  return (
    <Layer kind="modal" title="expand, migrate, contract" eyebrow="delivery.updated · 3 prs instead of 1" onClose={() => closeLayers(['modal'])} width={720} anchor="ms-rollout-modal"
      footer={<><button type="button" class="ms-btn" onClick={() => closeLayers(['modal'])}>close</button><button type="button" class="ms-btn primary" onClick={() => closeLayers(['modal'])}>open pr #213 · expand</button></>}>
      <ol class="ms-prs">
        <li>
          <header><b>pr #213 · expand</b><span class={`ms-check ${backward ? 'pass' : 'fail'}`}>{backward ? '✓ backward' : '✕ backward'}</span><span class={`ms-check ${full ? 'pass' : 'fail'}`}>{full ? '✓ full' : '✕ full'}</span></header>
          <ul class="ms-diff">{changes.map((change) => <li key={change.path} class={change.kind}><span class="ms-diff-sign" aria-hidden="true">+</span><code>payload.{change.path}</code><span class="ms-diff-kind">{kindLabel[change.kind]} · {change.after}</span></li>)}</ul>
          <p class="ms-muted">checked in your browser with the same checker ci runs (packages/events/src/compat.ts).</p>
        </li>
        <li><header><b>prs #214–216 · migrate</b><span class="ms-check pass">counter · shop-tracking · notifications</span></header><p class="ms-muted">each consumer switches to eta.earliest / eta.latest and carrierId behind a feature flag; read logs prove zero reads of etaMinutes.</p></li>
        <li><header><b>pr #217 · contract (v4)</b><span class="ms-check">after 14 days of zero reads</span></header><p class="ms-muted">removes etaMinutes and carrier. ci passes because no declared consumer reads them anymore.</p></li>
      </ol>
    </Layer>
  );
}
