<script lang="ts">
  let language: 'EN' | 'KR' | 'JP' = 'EN';
  const signals = [
    { market: 'Seoul', artist: 'AERA', moment: 'chorus lift · 00:42', score: '.91' },
    { market: 'Tokyo', artist: 'NAMI', moment: 'bridge replay · 01:18', score: '.86' },
    { market: 'LA', artist: 'Lumen', moment: 'hook share · 00:19', score: '.82' }
  ];
</script>

<svelte:head><title>Pulse · Performance intelligence</title><meta name="description" content="Synthetic entertainment performance intelligence."/></svelte:head>
<header><a href="/">IM</a><strong>Pulse</strong><nav>Intelligence　Distribution　AI harness</nav><div>{#each ['EN','KR','JP'] as item}<button class:active={language===item} onclick={()=>language=item as typeof language}>{item}</button>{/each}</div></header>
<main><section class="intro"><span>LA 09:18 · Seoul 01:18 · Tokyo 01:18</span><h1>See the moment.<br/><em>Prove the signal.</em></h1><p>Market intelligence, distribution actions, and the model release share one evidence trail.</p></section><section class="content"><div class="chart"><div><span>Cross-market completion</span><strong>live synthetic signal</strong></div><svg viewBox="0 0 900 300"><path class="grid" d="M0 60H900M0 150H900M0 240H900"/><path class="line" d="M0 245 C120 220 180 250 260 175 S390 125 470 150 S610 190 680 85 S810 55 900 70"/><circle cx="680" cy="85" r="7"/></svg></div><aside><span>✦ Simulated AI</span><h2>Ask Pulse</h2><p>“Why is Seoul moving before LA?”</p><button>Stream grounded answer →</button><small>3 sources · trace available</small></aside></section><section class="signals">{#each signals as signal}<article><small>{signal.market}</small><h3>{signal.artist}</h3><p>{signal.moment}</p><strong>{signal.score}</strong></article>{/each}</section></main>
<footer>All names are fictitious · data is synthetic · AI behavior is simulated in v0.1</footer>

<style>
  :global(*){box-sizing:border-box}:global(body){margin:0;background:#110d1c;color:#f9f5ff;font-family:Geist,system-ui,sans-serif}header{height:64px;display:flex;align-items:center;gap:14px;padding:0 4vw;border-bottom:1px solid #352c4b;background:#110d1cee;position:sticky;top:0;z-index:3}header>a{display:grid;width:32px;height:32px;place-items:center;border-radius:9px;background:#ff4f9a;color:#110d1c;text-decoration:none;font-weight:900;font-size:11px}nav{margin:auto;color:#a79bb8;font-size:12px}header div{display:flex;padding:3px;border:1px solid #352c4b;border-radius:9px}header button{border:0;background:transparent;color:#a79bb8;padding:6px 8px;border-radius:6px}.active{background:#45d6f5!important;color:#110d1c!important}.intro{padding:10vh 6vw 8vh}.intro>span{color:#45d6f5;font:700 11px ui-monospace,monospace;text-transform:uppercase;letter-spacing:.12em}.intro h1{margin:20px 0;font-size:clamp(60px,9vw,130px);line-height:.85;letter-spacing:-.065em}.intro em{font-style:normal;color:#ff4f9a}.intro p{max-width:670px;color:#a79bb8;font-size:18px;line-height:1.6}.content{display:grid;grid-template-columns:1fr 320px;gap:12px;padding:0 6vw}.chart,aside,.signals article{border:1px solid #352c4b;border-radius:18px;background:#1a1528}.chart{padding:25px}.chart>div{display:flex;justify-content:space-between}.chart strong{color:#45d6f5;font:700 10px ui-monospace,monospace}.chart svg{width:100%;margin-top:25px}.grid{fill:none;stroke:#352c4b}.line{fill:none;stroke:#ff4f9a;stroke-width:5;stroke-linecap:round;stroke-dasharray:1200;animation:draw 2s ease both}.chart circle{fill:#45d6f5}aside{padding:24px;background:#45d6f510;border-color:#45d6f5}aside>span{color:#45d6f5;font-size:12px;font-weight:800}aside h2{font-size:32px;margin:22px 0 12px}aside p{color:#a79bb8}aside button{width:100%;margin-top:30px;padding:13px;border:0;border-radius:11px;background:#45d6f5;color:#110d1c;font-weight:800}aside small{display:block;margin-top:14px;color:#a79bb8}.signals{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:12px 6vw 90px}.signals article{position:relative;padding:22px}.signals small{color:#45d6f5}.signals h3{font-size:30px;margin:18px 0 5px}.signals p{color:#a79bb8}.signals strong{position:absolute;right:22px;top:22px;color:#ff4f9a;font-size:22px}footer{padding:30px;text-align:center;border-top:1px solid #352c4b;color:#a79bb8;font-size:12px}@keyframes draw{from{stroke-dashoffset:1200}to{stroke-dashoffset:0}}@media(max-width:750px){nav{display:none}.content,.signals{grid-template-columns:1fr}.intro h1{font-size:65px}}
</style>

