// Emits src/themes.css from src/themes.json so CSS and TypeScript share one token contract.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const themes = JSON.parse(readFileSync(resolve(root, 'src/themes.json'), 'utf8'));

export function renderThemes(source) {
  const blocks = Object.entries(source).map(([name, theme]) => {
    const vars = [
      ...Object.entries(theme.color).map(([key, value]) => `--${key}:${value}`),
      ...Object.entries(theme.font).map(([key, value]) => `--font-${key}:${value}`),
      ...Object.entries(theme.shape).map(([key, value]) => `--${key}:${value}`),
      ...Object.entries(theme.motion).map(([key, value]) => `--${key}:${value}`),
      `--shade:${isDark(theme.color.ground) ? '#000000' : theme.color.ink}`,
      '--scrim:color-mix(in srgb,var(--shade) 58%,transparent)',
      '--scrim-light:color-mix(in srgb,var(--shade) 22%,transparent)',
      '--elevation:0 24px 70px color-mix(in srgb,var(--shade) 18%,transparent)',
      '--ai-soft:color-mix(in srgb,var(--ai) 10%,var(--surface))',
      '--accent-soft:color-mix(in srgb,var(--accent) 12%,var(--surface))',
      '--risk-soft:color-mix(in srgb,var(--risk) 11%,var(--surface))',
      '--success-soft:color-mix(in srgb,var(--success) 12%,var(--surface))',
      '--warn-soft:color-mix(in srgb,var(--warn) 14%,var(--surface))'
    ];
    const selector = name === 'portfolio' ? `:root,[data-theme='portfolio']` : `[data-theme='${name}']`;
    return `${selector}{${vars.join(';')};color-scheme:${isDark(theme.color.ground) ? 'dark' : 'light'}}`;
  });
  return `/* Generated by scripts/emit-css.mjs from themes.json — do not edit by hand. */\n${blocks.join('\n')}\n`;
}

function isDark(hex) {
  const [r, g, b] = [1, 3, 5].map((index) => parseInt(hex.slice(index, index + 2), 16));
  return (r * 299 + g * 587 + b * 114) / 1000 < 128;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(resolve(root, 'src/themes.css'), renderThemes(themes));
}
